// lib/pdf.ts
import jsPDF from "jspdf";
import { FitnessPlan, Day } from "./types";

const days: Day[] = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"];

const capitalize = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);

export async function exportToPDF(plan: FitnessPlan, userName?: string) {
  const pdf = new jsPDF();
  let y = 30;

  pdf.setFontSize(22);
  pdf.setFont("helvetica", "bold");
  pdf.text("Your AI Fitness & Diet Plan", 105, y, { align: "center" });
  y += 20;

  for (const day of days) {
    const workout = plan.workoutPlan[day];
    const diet = plan.dietPlan[day];

    if (y > 260) {
      pdf.addPage();
      y = 20;
    }

    // === WORKOUT SECTION ===
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text(`${capitalize(day)} – Workout`, 20, y);
    y += 8;

    pdf.setFontSize(12);
    pdf.setFont("helvetica", "normal");
    pdf.text(`Focus: ${workout.focus}`, 25, y);
    y += 10;

    workout.exercises.forEach((ex) => {
      const line = `• ${ex.name}: ${ex.sets} × ${ex.reps}, Rest: ${ex.rest}`;
      pdf.text(line, 30, y);
      y += 7;
    });

    if (workout.motivation) {
      pdf.setFont("helvetica", "italic");
      pdf.text(`"${workout.motivation}"`, 30, y);
      pdf.setFont("helvetica", "normal");
      y += 7;
    }

    if (workout.tips.length > 0) {
      pdf.setFontSize(10);
      pdf.text("Tips:", 30, y);
      y += 6;
      workout.tips.forEach((tip) => {
        pdf.text(`  - ${tip}`, 35, y);
        y += 5;
      });
      pdf.setFontSize(12);
    }

    y += 10;

    // === DIET SECTION ===
    if (y > 240) {
      pdf.addPage();
      y = 20;
    }

    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    pdf.text(`${capitalize(day)} – Diet`, 20, y);
    y += 8;

    if (diet.summary) {
      pdf.setFontSize(12);
      pdf.setFont("helvetica", "normal");
      pdf.text(`Summary: ${diet.summary}`, 25, y);
      y += 8;
    }

    diet.meals.forEach((meal) => {
      const line = `• ${meal.name}: ${meal.description} (${meal.calories} kcal)`;
      const split = pdf.splitTextToSize(line, 160);
      pdf.text(split, 30, y);
      y += split.length * 6;
    });

    y += 15; 
  }
  pdf.setFontSize(10);
  pdf.setTextColor(100);
  pdf.text(`Personalized for: ${userName || "You"}`, 105, y, { align: "center" });
  pdf.text("Generated by AI Fitness Coach", 105, 290, { align: "center" });
  pdf.save("ai-fitness-plan.pdf");
}